### ISSUE TITLE
Gitignore project files

### ISSUE THREAD

**Issue by harikt** [rubykv/student-marksheet#1]
Hi, 

How about 

* add project settings to gitignore ?
* add a licence
* a readme ;)

Thank you.

**Comment by rubykv** [comment]
All done :) Thanks!

**Comment by harikt** [comment]
you missed one. Adding to gitignore and remove the project and settings ;) .

**Comment by rubykv** [comment]
Updated .gitignore but not sure if I can delete the existing .settings folder. Any help is appreciated :)

**Comment by harikt** [comment]
Do you need .project file ?
